### PR TITLE
fix(gatsby-theme-minimal-blog): Use correct h1 on all pages

### PR DESCRIPTION
**Pull request by markjackson02**
From an SEO perspective it makes sense for the post title to be an H1 tag. No change to visual styling.

### CODE REVIEW

**Comment by markjackson02** [comment]
When I run `yarn run lint` I'm getting 15,200 errors, not sure why? 

Here are some as an example:
```
C:\Users\markj\workspace\gatsby-themes\www\src\webgl\model.tsx
    1:3    error    Delete `␍`                                     prettier/prettier
    2:53   error    Delete `␍`                                     prettier/prettier
```

**Comment by markjackson02** [comment]
When I try to run e2e tests I am getting this error

```
$ ./scripts/e2e-dev.sh "minimal-blog"
7:50:13 PM - Starting compilation in watch mode...
[0]
[1] C:\Users\markj\workspace\gatsby-themes\node_modules\lazy-ass\index.js:117
[1]       throw err;
[1]       ^
[1]
[1] Error: expected <NPM script name that starts server> <url or port> <NPM script name that runs tests>
[1] example: start-test start 8080 test
[1] see https://github.com/bahmutov/start-server-and-test#use
[1]
[1]     at lazyAssLogic (C:\Users\markj\workspace\gatsby-themes\node_modules\lazy-ass\index.js:110:14)
[1]     at lazyAss (C:\Users\markj\workspace\gatsby-themes\node_modules\lazy-ass\index.js:115:28)
[1]     at Object.getArguments (C:\Users\markj\workspace\gatsby-themes\node_modules\start-server-and-test\src\utils.js:51:5)
[1]     at Object.<anonymous> (C:\Users\markj\workspace\gatsby-themes\node_modules\start-server-and-test\src\bin\start.js:10:22)
[1]     at Module._compile (internal/modules/cjs/loader.js:1137:30)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
[1]     at Module.load (internal/modules/cjs/loader.js:985:32)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
[1]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
[1]     at internal/main/run_main_module.js:17:47
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
[1] yarn start-server-and-test 'yarn workspace minimal-blog develop:cypress' http://localhost:8000 cy:open exited with code 1
--> Sending SIGTERM to other processes..
[0] yarn tsc:compile:watch exited with code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by LekoArts** [comment]
Thank you for the initial commit and finding of this issue!

**Comment by LekoArts** [comment]
```
Successfully published:
 - @lekoarts/gatsby-theme-minimal-blog@2.6.5
```

**Pull request merged**
